# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1045, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_start_stop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start_stop.setObjectName("btn_start_stop")
        self.gridLayout_2.addWidget(self.btn_start_stop, 1, 0, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.acc_t_layout = QtWidgets.QVBoxLayout()
        self.acc_t_layout.setObjectName("acc_t_layout")
        self.gridLayout.addLayout(self.acc_t_layout, 0, 0, 1, 1)
        self.acc_f_layout = QtWidgets.QVBoxLayout()
        self.acc_f_layout.setObjectName("acc_f_layout")
        self.gridLayout.addLayout(self.acc_f_layout, 0, 1, 1, 1)
        self.gyro_t_layout = QtWidgets.QVBoxLayout()
        self.gyro_t_layout.setObjectName("gyro_t_layout")
        self.gridLayout.addLayout(self.gyro_t_layout, 1, 0, 1, 1)
        self.gyro_f_layout = QtWidgets.QVBoxLayout()
        self.gyro_f_layout.setObjectName("gyro_f_layout")
        self.gridLayout.addLayout(self.gyro_f_layout, 1, 1, 1, 1)
        self.angles_t_layout = QtWidgets.QVBoxLayout()
        self.angles_t_layout.setObjectName("angles_t_layout")
        self.gridLayout.addLayout(self.angles_t_layout, 2, 0, 1, 1)
        self.angles_f_layout = QtWidgets.QVBoxLayout()
        self.angles_f_layout.setObjectName("angles_f_layout")
        self.gridLayout.addLayout(self.angles_f_layout, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1045, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_start_stop.setText(_translate("MainWindow", "Start/Stop"))
